### ISSUE TITLE
Rename PHETIO -> PHET_IO in constants

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#104]
As part of https://github.com/phetsims/phet-io/issues/1361, we decided that "PhET-iO" named as a constant should be "PHET_IO".

There are multiple usages in this sim.

**Comment by zepumph** [comment]
Please review @pixelzoom

**Comment by pixelzoom** [comment]
Typical relationship between constants and variables is to insert underscores in constants where camelcase occurs in var names.  E.g.  `myBigFatWedding` and `MY_BIG_FAT_WEDDING`.   What you've done here violates that convention.  It should be either `phetioDocumention` and `PHETIO_DOCUMENTATION`, or `phetIoDocumentation` and `PHET_IO_DOCUMENTATION`.   That said...

Back to @zepumph, so that you're aware of the inconsistency.  Up to you whether to do anything. If we were doing any programmatic conversion or searching of names, I'd be more concerned.

**Comment by pixelzoom** [comment]
I've added `phetioComponentOptions: DEFAULT_PHET_IO_COMPONENT_OPTIONS` using the recommended naming convention.

**Comment by zepumph** [comment]
Anything else here @pixelzoom?
