### ISSUE TITLE
Reset All button pointer areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#120]
See phetsims/friction#65.  The pointer area for touch for reset all seems like it is meant to be a bit larger.  @pixelzoom and @amanda-phet to determine if this is appropriate.
For https://github.com/phetsims/QA/issues/227

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/friction/issues/65#issuecomment-443796439:
> PhET sims typically do NOT dilate the pointer areas for the Reset All button because (1) the button is plenty large, and (2) we don't want the user to hit this button unless they really intend to.

So I'm going to push back hard on this one.

**Comment by pixelzoom** [comment]
Also... If we did want to dilate pointer areas for the Reset All button, that should be done uniformly in `SCENERY_PHET/ResetAllButton`, not in sim-specific code.

**Comment by amanda-phet** [comment]
No need to do anything sim-specific for that button. As @pixelzoom said, the reset-all button should be very intentionally pressed and usually does not have a larger touch area. Also, I agree, this is a universal component that should have universal behavior- if we need a discussion about touch on small devices we should include Ariel and Kathy.

**Comment by ariel-phet** [comment]
@pixelzoom I do think this is a tad sim specific. It is nice for the Reset All button to have a bit of dilation for the touch area in cases where no other interactive UI components are close (the Friction sim being a reasonable example).

I would be fine if we wanted to add a default dilation (it looks like what Sam pushed in friction was a bit of overkill), but there may be some cases where such UI components are fairly tight to the button. For smaller devices, in general, having optimized touch areas is nice.

**Comment by pixelzoom** [comment]
@ariel-phet This issue was not created because of any reported usability problem.  It was reported because of something done in another sim (Friction).   I agree that if there is a usability problem here, then it should be addressed.  But how is the current touchArea of the Reset All button not sufficient for this sim?  I have no problem clicking the Reset All button on any device, even my tiny Android tablet and even tinnier iPhone 4s.

**Comment by ariel-phet** [comment]
@pixelzoom fair point. Was just looking at a few other sims, looks like in things like Masses and Springs the play/pause button is dilated to the default size of the Reset All button.

![massessprings](https://user-images.githubusercontent.com/4051174/49392837-dcaf7080-f6ec-11e8-8300-fef727f0ebca.PNG)

Furthermore, it looks like the line of request here came from Sam asking in code review if we should dilate the button in Friction a bit (no usability concern necessarily) --> @phet-steele seeing that and suggesting the change in other sims (like Blackbody) --> @KatieWoe following that lead. My mushy brain may have also agreed initially since I think there was a time when the Reset All button had various sizes in various sims, but it seems to be pretty standard these days.

Closing, will let @KatieWoe know to reserve such a suggestion when a usability issue is present.
