### ISSUE TITLE
graphed curves are thin in iframe

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#124]
For https://github.com/phetsims/QA/issues/227.  Found on chromebook Chadwick when in iframe, was not present in full screen.  The resolution of the screen seems to cause the line to become very thin when a is large on any screen, though sometimes unevenly.
Per @pixelzoom 
>It’s a resolution problem, not solvable unless we make the curves much thicker.  But go ahead and create an issue.

![pastedimage](https://user-images.githubusercontent.com/41024075/49471077-34bba500-f7c9-11e8-9e03-5470aa0e0dd8.png)

**Comment by pixelzoom** [comment]
This would be an issue with any sim that is scaled down this severely.  The line widths used for the curves (`KITES/Shape`) are not designed to be used with a display that is this small.

FYI, here are the `lineWidth` values for the various graphed curves, from `GQConstants`:

```js
    // line widths
    INTERACTIVE_QUADRATIC_LINE_WIDTH: 4,
    SAVED_QUADRATIC_LINE_WIDTH: 3,
    QUADRATIC_TERMS_LINE_WIDTH: 2, // y = ax^2, y = bx, y = c
    AXIS_OF_SYMMETRY_LINE_WIDTH: 3,
    DIRECTRIX_LINE_WIDTH: 3,
    POINT_ON_PARABOLA_LINE_WIDTH: 3, // lines that connect point to focus and directrix
```

@amanda-phet If you agree that we should do nothing about this, please close.  Otherwise please provide specifics on what you'd like to change.

**Comment by KatieWoe** [comment]
This seems particularly odd as it depends on position. 
![linesareodd](https://user-images.githubusercontent.com/41024075/49474206-5b7dd980-f7d1-11e8-8be4-09751f4470e6.gif)

**Comment by pixelzoom** [comment]
> This seems particularly odd as it depends on position.

Yes, that's what happens when there are more positions for the curve than there are pixels.

**Comment by amanda-phet** [comment]
Thanks for making a record @KatieWoe . If we decide to truly support lower-res screens in the future I imagine we will discuss this as a universal issue.
