### ISSUE TITLE
Why rename saveEraseButtonGroup?

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/graphing-quadratics#125]
I'm working on the Featured list, and in the latest studio this PhETiO iD was renamed... it had been. 
graphingQuadratics.exploreScreen.view.equationAccordionBox.saveEraseButtonGroup.visibleProperty
Now it is 
graphingQuadratics.exploreScreen.view.equationAccordionBox.buttonGroup.visibleProperty

imo, the new name is too vague for an instructional designer, and I preferred the original name.

what was the motivation for the change?

**Comment by pixelzoom** [comment]
It's the only group of buttons in the accordion box, so "buttonGroup" is a sufficiently descriptive name.  And under "buttonGroup", you'll find "saveButton" and "eraseButton".  So "saveEraseButtonGroup" is redundant and overly specific. Also, if we decided to add another button in a future enhancement, a name like "saveEraseButtonGroup" would be a liability.

**Comment by samreid** [comment]
What if we add another button group in a future enhancement?

**Comment by pixelzoom** [comment]
It is highly unlikely that we'll ever add any more buttons to this accordion box.  If we did add a button, I've venture to guess that it would be more likely to be added to the existing button group - we rarely have need (or justification) for multiple button groups. 

In any case... Future-proofing the name is the secondary argument. The primary argument is that there is no need for such specificity in the name.

**Comment by pixelzoom** [comment]
Another reason for the name change...  `SaveEraseButtonGroup` used to exist as a separate class, in its own .js file.   Since it is used solely by this accordion box, it is now inner type `ButtonGroup` of `GQAccordionBox` (the base class for accordion boxes in this sim).   The code looks like this:

```js
      // Buttons at the bottom of the accordion box
      const buttonGroup = new ButtonGroup( model, {
        tandem: options.tandem.createTandem( 'buttonGroup' )
      } );
```

In keeping with PhET conventions, the variable name (`buttonGroup`) matches the class name (`ButtonGroup`), and the tandem name (`'buttonGroup'`) matches the variable name.

**Comment by pixelzoom** [comment]
Another reason for the name change...  `SaveEraseButtonGroup` used to exist as a separate class, in its own .js file.   Since it is used solely by this accordion box, it is now inner type `ButtonGroup` of `GQAccordionBox` (the base class for accordion boxes in this sim).   The code in `GQAccordionBox` looks like this:

```js
      // Buttons at the bottom of the accordion box
      const buttonGroup = new ButtonGroup( model, {
        tandem: options.tandem.createTandem( 'buttonGroup' )
      } );
```

In keeping with PhET conventions, the variable name (`buttonGroup`) matches the class name (`ButtonGroup`), and the tandem name (`'buttonGroup'`) matches the variable name.  

I see no benefit to violating these conventions, or renaming the `ButtonGroup` inner class.

**Comment by pixelzoom** [comment]
I should also mention that `buttonGroup` was given the OK by designers in last Thursday's design meeting, where we discussed this specifically.

**Comment by pixelzoom** [comment]
Here's the tree for the _Explore_ screen.

Instances = "Featured":

![screenshot_918](https://user-images.githubusercontent.com/3046552/49472935-eeb51000-f7cd-11e8-87be-5139dfe4320e.png)

Instances = "All":

![screenshot_919](https://user-images.githubusercontent.com/3046552/49472939-f2e12d80-f7cd-11e8-90fb-0c8cca1d705e.png)

@kathy-phet Would you be happier with "buttonGroup" if "saveButton" and "eraseButton" where shown in "Featured" mode?   We had previously decided not to feature these buttons because we wanted them to be manipulated as a group, not individually.

**Comment by pixelzoom** [comment]
One more argument against specificity in the name...  

"interactiveEquationNode" appears 4 places in the tree, once for each screen.  It describes the logical function of that UI component. If we followed the approach of "saveEraseButtonGroup", then we would consider names like "abcInteractiveEquatioNode", to indicate what the subcomponents are.  But we don't (and shouldn't) put that information in the name - the user is expect to expand the tree to see what the subcomponents are.

**Comment by kathy-phet** [comment]
I don't recall discussing it last week, but it sounds like there is consensus here, so I will just make the change in the google doc of featured components. And no, I don't think we should feature the save and erase buttons separately. 

Closing.
