### ISSUE TITLE
Coordinates not visible once off graph

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#153]
https://github.com/phetsims/qa/issues/687

In the Focus & Directrix Screen, I wasn't sure if the focus coordinates should still be visible even when the point is off of the graph. This also happens with vertex coordinates in the Standard Form screen.

https://drive.google.com/file/d/1NO1VEzMTavmp4J7H8RNQOCMQ207TGQz0/view?usp=sharing

<img width="963" alt="Screen Shot 2021-08-05 at 12 46 07 PM" src="https://user-images.githubusercontent.com/87318828/128390943-67b27825-dfca-45b3-989a-421b563c61f0.png">

<img width="963" alt="Screen Shot 2021-08-05 at 1 08 02 PM" src="https://user-images.githubusercontent.com/87318828/128392195-367fb4ef-6674-424b-83af-832095040b45.png">

**Comment by pixelzoom** [comment]
Coordinates are attached to interactive points (which PhET calls "manipulators"), and we therefore generally do not show them if the manipulator is off that graph.  So in this case, it's correct that the Focus coordinates are not shown.

But this raises another question: Should the Focus manipulator be constrained to always be on the graph?  We do constrain the Point on Parabola ("Point") manipulator - if you drag the Vertex manipulator such that the Point would be off the graph, the Point is automatically moved to keep it on the graph.  Maybe we didn't do that for the Focus manipulator because focus alters the shape (and equation) of the curve, while the Point does not.  Or maybe it was an oversight. 

Note that the Vertex manipulator is constrained to dragging within the bounds of x=[-6,6] and y=[-6,6], specifically so that we can keep the Point manipulator visible.  So there's no issue with the Point or Focus having to "hop over" the Vertex at the edges of the graph.

My instinct is to leave this as is. We want the student to be able to move the Vertex and see how that affects the curve.  If we're also automatically moving the Focus as the student moves the Vertex, then it will become difficult/confusing to see how moving the Vertex affects the curve.

@arouinfar thoughts?

**Comment by pixelzoom** [comment]
Note that we also don't do anything to keep the Directrix (horizontal green dashed line) on the graph.  And the Directrix is a function of the Focus point.  So if we mess with trying to keep the Focus on the graph, should we also try to keep the Directrix on the graph?  I can see why we did not do this.

**Comment by pixelzoom** [comment]
@amanda-phet Also please comment on whether it's OK that the Focus coordinates are not shown when the Focus is off the graph.  That was the issue that @Nancy-Salpepi's originally reported, and you should verify whether that's OK.  If it's not OK, this will be an expensive change - we'll need to find another way to display Focus coordinates when the manipulator is not visible.

**Comment by amanda-phet** [comment]
It is ok to not see the coordinates if the manipulator is outside the graph viewing area. 

I don't want to limit the manipulator to always being visible, because if dragging a parabola caused the focus to be limited, it would change the graph of the parabola, and that seems like a poor user experience. 

Let's leave the functionality and visibility for the things discussed in this issue as-is. Thanks for asking though @Nancy-Salpepi .
