### ISSUE TITLE
Equation for y=ax^2 lies behind curves causing view to sometimes be obstructed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#157]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.4

**Browser**
chrome 92.0.4515.131

**Problem description**
https://github.com/phetsims/qa/issues/692

In the explore screen, the equations lie in front of the curves/lines except for y=ax^2. In some instances, the equations is blocked and unreadable. 

**Steps to reproduce**
Here is one instance:

1. In the Explore screen, check all options under "Quadratic Terms."
2. Check "Equations"
3. Set "a" to .42 , set "b" to .9, and set "c" to 1.3 using the sliders. 

**Visuals**
Equation is behind curve:
<img width="384" alt="Screen Shot 2021-08-17 at 10 47 58 AM" src="https://user-images.githubusercontent.com/87318828/129748242-66ec48c7-8a5f-401f-8539-82efae61991e.png">

Equations are in front:
<img width="304" alt="Screen Shot 2021-08-17 at 10 36 32 AM" src="https://user-images.githubusercontent.com/87318828/129748366-a9acc662-5fba-4a07-b4e8-0317fb747cea.png">

<img width="304" alt="Screen Shot 2021-08-17 at 10 36 14 AM" src="https://user-images.githubusercontent.com/87318828/129748413-7d0c0edf-f483-4faf-810f-43dff806a381.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-rc.1/phet/graphing-quadratics_all_phet.html
Version: 1.2.0-rc.1 2021-08-09 23:17:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language: en-US
Window: 1452x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by amanda-phet** [comment]
I think the equation and curve for the main (red) curve are always in the front, since those are the most important. I just checked, and y=ax^2 seemed consistent with the other terms (y=bx and y=c) in that their equations are behind the red curve. We had to accept that in some cases, equations might be occluded, such as in this case: 
![image](https://user-images.githubusercontent.com/7852916/129788621-5fc201fa-2807-4922-88b2-ebddca32fd5f.png)

Since I am not seeing an inconsistency with how equations are treated, I'll close this issue. However if I'm misunderstanding, or there is more to discuss, please re-open.
