### ISSUE TITLE
Rendering order is incorrect for snapshot restored via PhET-iO.

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#165]
**Test device**
MacBook Air

**Operating System**
11.4

**Browser**
chrome and safari

**Problem description**
https://github.com/phetsims/qa/issues/692

Studio Wrapper:

In the Vertex Form and Focus and Directrix screens, the parabola (black) turns gray in the area that overlaps the equation of the snapshot parabola. 

In the Explore and Standard Form screens, The snapshot equation and snapshot parabola are in front of the main parabola (orange). The parabola remains orange here (unlike the above scenario). 

**Steps to reproduce**

1. Check Equations option
2. Click the snapshot tool.
3. Then adjust the parabola so that the lines/equations overlap. 
       Ex: In Focus and Directrix Screen: p = 2.0 h= -0.5 and k = -1.6
       Ex: In Standard Form Screen: a = 1, b=5, c=0
4. Launch sim

**Visuals**
Focus and Directrix Screens--Studio on top and Launched Sim underneath:
<img width="950" alt="Screen Shot 2021-08-23 at 11 33 25 AM" src="https://user-images.githubusercontent.com/87318828/130475356-85b729b6-b4dc-47ee-8e00-0d35a47944ab.png">

Standard Form Screen--Studio on left and Launched Sim on right:
<img width="681" alt="Screen Shot 2021-08-23 at 11 36 13 AM" src="https://user-images.githubusercontent.com/87318828/130475783-3251e869-b1d8-4be5-8c42-126823a31850.png">

**Comment by Nancy-Salpepi** [comment]
Also seen in State wrapper

**Comment by Nancy-Salpepi** [comment]
Screenshot parabola also moves forward when other equations aside from the main are involved:

<img width="470" alt="Screen Shot 2021-08-23 at 12 33 08 PM" src="https://user-images.githubusercontent.com/87318828/130484727-e5ffdc93-eab5-4114-8d03-9dab2e064926.png">

<img width="470" alt="Screen Shot 2021-08-23 at 12 37 59 PM" src="https://user-images.githubusercontent.com/87318828/130484751-df84aab4-a6c4-4c01-9504-71a80cbbf6e6.png">

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.  The rendering order is different - saved curves and equations are in front, when they should be behind.  This is probably due to the order of restoring elements.   I'll investigate.

**Comment by pixelzoom** [comment]
Here's the relevant code, in GQGraphNode.js:

```js
    // When the saved quadratic changes...
    model.savedQuadraticProperty.link( savedQuadratic => {
      if ( savedQuadratic ) {
        ...
        savedLineNode = new QuadraticNode( ... );

        // Add it in the foreground, so the user can see it.
        // See https://github.com/phetsims/graphing-quadratics/issues/36
        allLinesParent.addChild( savedLineNode );
      }
    } );

    // When quadraticProperty changes, move saved line to background.
    // See https://github.com/phetsims/graphing-quadratics/issues/36
    model.quadraticProperty.link( quadratic => {
      savedLineNode && savedLineNode.moveToBack();
    } );
```

So when the user took a snapshot (`savedQuadraticProperty`), we want the snapshot to be in the foreground "so the user can see it".    For example: In the Explore screen, immediately after pressing the snapshot button, the sim (correctly) looks like this in Studio and in the Preview Sim:

<img width="478" alt="screenshot_1207" src="https://user-images.githubusercontent.com/3046552/130492140-175f4ba0-1df8-4ead-b4be-a8bbadf10f82.png">

As soon as the user makes a change to `quadraticProperty` (the primary quadratic), the snapshot then moves to the background.   

To fix this problem, I'll need to know (a) whether state is being restored, and (b) whether the snapshot is the same curve as the primary quadratic.   So something like this added to the listener for `savedQuadraticProperty`:

```js
        // When restoring state, move saved line to the background if it's not identical to quadraticProperty.
        // See https://github.com/phetsims/graphing-quadratics/issues/165
        if ( phet.joist.sim.isSettingPhetioStateProperty.value && !savedQuadratic.hasSameCoefficients( model.quadraticProperty.value ) ) {
          savedLineNode.moveToBack();
        }
```

**Comment by pixelzoom** [comment]
In the above commits, this was fixed in master and 1.2 branches. 

@Nancy-Salpepi please verify in master, or in this dev version that was built from master:
https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.0-dev.2/phet-io/

You should test these 2 situations to confirm that rendering order is correct:

(1) Immediately after pressing the snapshot button, but before making any other changes, the snapshot should be IN FRONT OF the primary quadratic.
(2) After pressing the snapshot button, then changing the primary quadratic, the snapshot should be BEHIND the primary quadratic. 

If this looks OK, please unassign yourself, and change the label to "status:fixed-awaiting-deploy".

**Comment by Nancy-Salpepi** [comment]
No issues.

**Comment by pixelzoom** [comment]
I investigated options (2). It's doable, but it's going to make the code mighty complicated.  I'm not convinced it's worth it, because I don't see the point in creating an initial state where the snapshot is completely covered by the primary quadratic.

That said, here's a "documentation patch" that I'd like to apply, regardless of which option we decide to go with:

<details>
<summary>Patch</summary>

```diff
Index: js/common/view/GQGraphNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GQGraphNode.js b/js/common/view/GQGraphNode.js
--- a/js/common/view/GQGraphNode.js	(revision 080cea8912e256c9d7e20a4c097979bc45cadd5f)
+++ b/js/common/view/GQGraphNode.js	(date 1630272230890)
@@ -115,19 +115,17 @@
         // See https://github.com/phetsims/graphing-quadratics/issues/36
         allLinesParent.addChild( savedQuadraticNode );
 
-        // When restoring state, move savedQuadraticNode to the background if savedQuadratic is NOT identical to
-        // quadraticProperty, because that means that the user changed quadraticProperty after taking the snapshot,
-        // and the primary quadratic should be in front. If savedQuadratic IS identical to quadraticProperty, we want
-        // to leave savedQuadraticNode in the foreground, and let the quadraticProperty listener below handle moving
-        // it to the back, when the user makes changes to quadraticProperty.
-        // See https://github.com/phetsims/graphing-quadratics/issues/165
+        // When restoring state, if savedQuadratic is identical to quadraticProperty, then leave it in front, so
+        // the user can see it. Otherwise move it to the back.
+        // See https://github.com/phetsims/graphing-quadratics/issues/165.
         if ( phet.joist.sim.isSettingPhetioStateProperty.value && !savedQuadratic.hasSameCoefficients( model.quadraticProperty.value ) ) {
           savedQuadraticNode.moveToBack();
         }
       }
     } );
 
-    // When quadraticProperty is changed BY THE USER, move the saved quadratic to the background.
+    // When a quadratic is saved, it is initially in front of quadraticProperty. Otherwise it wouldn't be visible
+    // because they are identical. When quadraticProperty is changed BY THE USER, move the saved quadratic to the background.
     // See https://github.com/phetsims/graphing-quadratics/issues/36 and https://github.com/phetsims/graphing-quadratics/issues/165.
     model.quadraticProperty.link( quadratic => {
       if ( !phet.joist.sim.isSettingPhetioStateProperty.value ) {
```

</details>

**Comment by pixelzoom** [comment]
@amanda-phet and I discussed this issue via Zoom.  She said supporting the case identified by @KatieWoe in https://github.com/phetsims/graphing-quadratics/issues/165#issuecomment-907465826 isn't a pedagocial concern, and we could publish 1.2 without addressing that case.  And even longterm, we could probably not address that case and it would never present a problem in practice.  So I've removed the "blocks-sim-publiction" label.

We also agreed that I'll spend a little more time on this, to see if I've overlooked a more straightforward way to address this.   If not, then we'll likely close this issue as "won't fix".

**Comment by pixelzoom** [comment]
I spent another 30 minutes on this, then discovered that add the additional Property will require not only instrumenting that one Property, but also instrumenting the graphs, so that they have a tandem that can be used to instrument that new Property.  But in GQGraphNode.js (where this happens), there is a very clear/explicit decision NOT to instrument graphs:

```js
    assert && assert( !options.tandem, 'GQGraphNode should not be instrumented' );
```

So continuing with this would also require revisiting the decision not to instrument graphs, deciding what the metadata should be for graph Properties, etc.   This is just not worth it, and we should live with this one case where restored state is a little "off".    

I'm going to clean up some code comments (to note that we're not addressing this) and we'll verify this again in the next RC.
