### ISSUE TITLE
Feature `rootsNode.*CoordinatesProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/graphing-quadratics#194]
For #180 

The `quadraticProperty` contains everything one might want to know about the quadratic except for the roots. Knowing the coordinates of roots seems like useful data, so I think it would be nice to feature `rootsNode.*CoordinatesProperty`.

I looked through the repo and notes docs to see if this had been considered before but didn't see anything. @pixelzoom if you know of a reason why these were omitted, please let me know. Otherwise, let's feature `rootsNode.*CoordinatesProperty`.

**Comment by pixelzoom** [comment]
I don't recall this being considered before. I went ahead and featured `rootsNode.leftCoordinatesProperty` and `rootsNode.rightCoordinatesProperty` in the above commits.

But there's another possibility, which may be a better UX... We could add the roots to QuadraticIO, so that they appear in the state object for the value of `quadraticProperty`.   @arouinfar thoughts?

**Comment by pixelzoom** [comment]
> ... We could add the `roots` to QuadraticIO, so that they appear in the state object for the value of quadraticProperty.

@arouinfar and I discussed this.  We're not going to do this because (1) no one has asked for it, (2) roots are kind of odd, see https://github.com/phetsims/graphing-quadratics/issues/146, and (3) adding roots to state will take a non-trivial amount of time, and likely involved other PhET-iO developers.   If someone asked for this in the future, we can add it then.

So... @arouinfar please review `rootsNode.leftCoordinatesProperty` and `rootsNode.rightCoordinatesProperty`. Close if OK.

**Comment by arouinfar** [comment]
Thanks for summarizing @pixelzoom. 

> So... @arouinfar please review `rootsNode.leftCoordinatesProperty` and `rootsNode.rightCoordinatesProperty`. Close if OK.

Looks good, closing.
