### ISSUE TITLE
What subtypes need to extend Tandem.required?

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#64]
Since GQCheckbox (the parent) is also required, that options block seems superfluous to me and @chrisklus.

Taking this one step further. `Checkbox.js` is also `Tandem.required`, so technically this check isn't needed in GQCheckbox either. That said I understand the desire to have at "sanity assignment" within the sim specific code just in case `Checkbox.js` changed for some reason in the future. In general the convention has become that all UI components are `Tandem.required`. I don't see that changing any time soon.

**Comment by zepumph** [comment]
From phet-io review in #14

**Comment by pixelzoom** [comment]
This is not specific to EquationsCheckbox, it's specific to all subclasses of Checkbox.

**Comment by pixelzoom** [comment]
... and subclasses of Slider.

**Comment by pixelzoom** [comment]
... and subclasses of AccordionBox.

**Comment by zepumph** [comment]
I was just commenting as such! (we have so much in common). Perhaps we should discuss a convention, as likely the whole hierarchy in  sim specific types doesn't need this option.

**Comment by pixelzoom** [comment]
Actually, my Slider and AccordionBox _do_ need `tandem: Tandem.required` because they create subcomponents using `options.tandem.createTandem`.

**Comment by zepumph** [comment]
Hey that makes a lot of sense!

**Comment by pixelzoom** [comment]
Unnecessary uses of `tandem: Tandem.required` were exclusively in Checkboxes, and were removed in the above commit. 

Those uses where there because my approach has been to (blindly) add `tandem: Tandem.required` to options for everything that needed to be instrumented, and not spend time inspecting the common-code subtypes.  I'm not at all convinced that `Tandem.required` is the appropriate default in common-code components, and there are exceptions to that convention (e.g. NumberDisplay).  So adding `tandem: Tandem.required` is a bit of defensive programming, and it doesn't hurt to have it there, regardless of what's in a common-code superclass.

Re convention... The safest convention is to add `tandem: Tandem.required` to default options wherever you intend to pass tandem via options.  It's absolutely required wherever you intend to use `options.tandem.createOptions` to create a tandem for a subcomponent.

**Comment by pixelzoom** [comment]
Hmmm... Based on my above comment, I'm wondering if I should have removed `tandem: Tandem.required` from Checkboxes.   If the convention ever changes such that Checkbox has `tandem: Tandem.optional`, then my code will be vulnerable to someone accidentally removing a tandem for one of my Checkboxes.

**Comment by zepumph** [comment]
>So adding tandem: Tandem.required is a bit of defensive programming

I think that is a good practice.

>Re convention... The safest convention is to add tandem: Tandem.required to default options wherever you intend to pass tandem via options. It's absolutely required wherever you intend to use options.tandem.createOptions to create a tandem for a subcomponent.

Agreed! I will update the how-to docs with this information

>Hmmm... Based on my above comment, I'm wondering if I should have removed tandem: Tandem.required from Checkboxes. If the convention ever changes such that Checkbox has tandem: Tandem.optional, then my code will be vulnerable to someone accidentally removing a tandem for one of my Checkboxes.

This seems like it could be fixed with a single required option in GQCheckbox.js.

**Comment by pixelzoom** [comment]
> This seems like it could be fixed with a single required option in GQCheckbox.js.

Indeed - I'll do that.

**Comment by pixelzoom** [comment]
@zepumph ready for review, close if OK.

**Comment by zepumph** [comment]
Looks great thanks.
