### ISSUE TITLE
Convert usages of SimpleDragHandler to DragListener?

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#66]
From #14,

This is not something I am necessarily recommending, but I wanted to discuss how difficult this would be. 

The thought spawns from recent work the PhET-iO team has done in instrumenting DragListener to use the new Emitter pattern for events.

There are two ways to proceed before sim publication. 
1. Convert to DragListener, where the "new/thoughtful/stable" api work has already been done.
2. Bump priority to phetsims/scenery#843 to update SimpleDragHandler to the new Emitter pattern.

Either way, the goal is to create a consistent and more maintainable phet-io data stream.

I also believe that this issue should begin to create the convention in how we generally proceed with listeners. In faraday's law it worked very well to convert over to DragListener, and it only took a matter of minutes. I don't think it will always be that easy, but when it is we should take advantage.

**Comment by pixelzoom** [comment]
Mentioning @ariel-phet, since there's a management component to this.

I would love to use `DragListener`, and I've asked about its status before and during implementation of at least the last 5 sims that I've worked on.  And it pains me to create new uses of `SimpleDragHandler` - especially for über-complicated handlers like the ones in Equality Explorer. 

But `DragListener` has been a work in progress for 5+ years, see https://github.com/phetsims/scenery/issues/131.  The prototype was checked in on 2/13/17.  And while I've heard repeatedly that it's about to be finished, that hasn't happened.  The more times that happens, the less inclined I am to use it until it's actually finished.  (Btw.. I'm not pointing fingers at anyone here, just stating facts. I realize that @jonathanolson has a lot of other things on his plate, other things come up, etc.)

For this sim, I asked about the status of `DragListener` as recently 9/24/18, see Slack archive https://phetsims.slack.com/archives/G6E0RA1T2/p1537814417000100.  The responses that I got from @jonathanolson were "but I’d hold off on moving to DragListener until I get things fully squared away", "Essentially in progress this week. I’ll probably be making a good number of changes/improvements", and "but I’d hold off on moving to DragListener until I get things fully squared away. I might want some cases to port myself as part of the process (if you don’t mind me touching that code)"  and then a bit of a flipflop to "I’m planning on updating usages if I break the API. And don’t hold off, just inform me".  

So... It's too late to port this sim to DragListener.  Dev testing starts Friday.  

Back to @zepumph to decide whether he wants to "bump priority of phetsims/scenery#843 to update SimpleDragHandler to the new Emitter pattern".

**Comment by zepumph** [comment]
>Back to @zepumph to decide whether he wants to "bump priority of phetsims/scenery#843 to update SimpleDragHandler to the new Emitter pattern".

Sounds good and I understand. I will bump priority accordingly

**Comment by zepumph** [comment]
Marking for dev meeting because I am a bit confused here. 

I see 23 usages of DragListener in over 5 different sims (not sure how many were published with it). I don't want to dwell on the GQ or EE decisions, but rather just want to figure out if we should be converting usages right now. This has been pertinent to PhET-iO recently.

**Comment by pixelzoom** [comment]
There are 108 occurrences of "SCENERY/input/SimpleDragHandler".  Is the goal really to port all of these to DragListener?  I'm betting not.  PhET-iO had better have a solution that works with SimpleDragHandler.

**Comment by pixelzoom** [comment]
After some reconsideration, I decided to attempt a port to DragListener.  My goal was to change as little as possible in the guts of my `start` and `drag` methods. There were a few speed bumps that involved consultation with @jonathanolson.  

Here are the issues that I encountered:

(1) DragListener and SimpleDragHandler `drag` method both have first argument `{Event} event`.  For SimpleDragHandler, `event.currentTarget` is as documented in Event.js -- it's the Node that you attached the listener to.  For DragListener, it's `null`, because apparently the drag becomes associated with a Pointer instead of the Node that you attached the DragListener to.  This is a subtle (and undocumented?) but significant difference.  I worked around this by passing in the target Node to my DragListener's constructor, which feels like a hack.

(2) To properly deal with multi-touch, we need to be able to interrupt drag cycles. For example, if `vertexVisibleProperty` becomes false while the vertex manipulator  is being dragged, then that drag cycle should end.  With SimpleDragHandler, the hack was to call `end(null)`.  With DragListener, it wasn't so obvious what to call.  I found `interrupt` and `release` methods, but didn't (and still don't) understand the difference.  @jonathanolson suggested skipping the DragListener methods and calling `interruptSubtreeInput` on the target Node. That seems to work nicely, and is definitely superior to the  SimpleDragHandler hack.

(3) The APIs are different for `start`, `drag` and `end`, see below.  For GQ, I only needed to adjust the method signatures.  If you happen to be using `trail`, I'm not sure what you do - probably ask @jonathanolson where else you can get it and change your code.

```js
// SimpleDragHandler
start( Event event, Trail trail )
drag( Event event, Trail trail )
end( Event event, Trail trail )

// DragListener
start( Event event, DragListener listener )
drag( Event event, DragListener listener )
end( DragListener listener )
```

Based on how I've used SimpleDragHandler in the past, any ports to DragListener are going to involve dealing mainly with these 2 differences.  @jonathanolson pointed out that some of the logic in my `start` and `drag` methods could be simplified by using additional DragListener features. But for a port, I think it's more appropriate to touch as little of the working code as possible, so what I did here will be my approach in future ports.  New uses of DragListener will certainly leverage its features.

So... I'm still not excited to be making big changes to input handling the day before I'm supposed to start dev testing.  But here we are.

**Comment by mbarlow12** [comment]
From dev meeting 10/18/18:
JO: for the most part, DragListener can be used in place of SimpleDragHandler. Changes may occur in the tracking of the node as it relates to underlying model properties.

Recommendation: Ping JO for initial usages to collaborate and avoid pitfalls.

**Comment by pixelzoom** [comment]
DragListener seems to be working, so I'll forgo the review of changes made to GQ, and we'll shake out any problems in dev testing.

Closing.
