### ISSUE TITLE
Default settings for "Vertex Form" and "Focus & Directrix" screens

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/graphing-quadratics#67]
When I was playing with the sim today, I noticed an inconsistency in the starting conditions for the vertex and the focus&directerix screens. 

In the vertex screen, the vertex point is off by default but the coordinates is on by default, so when you click the vertex you get both the point and the coordinates. 

In the focus&directerix screens, the draggable points are on by default but the coordinates are off by default. 

A suggestion for more consistency would be to always have the coordinates off by default across all screens (including on screen 2) since this seems like extra information that you wouldn't necessarily need. And having the draggable points on by default, so on both vertex and focus directorix these are available for you to drag when you first get to the vertex screen. 

I'll assign to Amanda to review suggestion.

**Comment by amanda-phet** [comment]
These conditions seem inconsistent, but they are all intentional... On the Standard and Vertex form screens the coordinates are on so that when the user changes the visibility of any of the features the coordinates will appear. The F&D screen has the interactive points on by default so students see them as they move the sliders or interact with them, but in the Vertex screen the interactive vertex is intentionally hidden so that users interact with the pickers first. 

All that to say, it's fine to make some changes, but all of the behavior is intentional and in interviews I was really pleased with the flow that students took through the sim. @kathy-phet let's chat in person after status.

**Comment by pixelzoom** [comment]
To add some history...

When I changed Vertex default to "off" on the Vertex Form screen, @amanda-phet explained to me that the motivation was to get the student to interact with the equation first, rather than immediately going to the more inviting vertex manipulator.

On the Focus & Directrix screen, we'd like the student to play with the focus and directrix manipulators first, so they are "on" by default.

I don't recall why the default for Coordinates is different on the 2 screens. Perhaps it's OK to make them "on" by default on _all_ screens?

**Comment by pixelzoom** [comment]
Decisions from meeting with @amanda-phet and @kathy-phet:

Changes:
- default to Vertex 'on' for "Vertex Form" screen, so that student sees correlation with h & k pickers
- default to Coordinates 'on' for "Focus & Directrix" screen, so that student sees correlation with slider values

**Comment by pixelzoom** [comment]
Done. @amanda-phet please review [1.0.0-dev.37](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.37/phet/graphing-quadratics_en_phet.html) and close this issue if it looks OK.

**Comment by amanda-phet** [comment]
Looks good. Thanks.
