### ISSUE TITLE
Overlapping labels and points

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#75]
As I've played with the sim I've noticed a few instances where equations, labels, and other parts of the sim overlap.  Some of these instances may be expected or unavoidable, but I'm documenting them here just in case.  Will update issue if more are found.  Descriptions of each image are above the picture.
For https://github.com/phetsims/QA/issues/211

Orange label covers equation on fourth screen.
![img_1320](https://user-images.githubusercontent.com/41024075/47225666-e1f26f00-d37b-11e8-9bbc-9ae4059823fd.PNG)
Line of curve covers the 10 axis label.
![img_1321](https://user-images.githubusercontent.com/41024075/47225667-e1f26f00-d37b-11e8-959c-44cc5741014b.PNG)
Draggable piece that examines line covers equation.
![img_1322](https://user-images.githubusercontent.com/41024075/47225668-e1f26f00-d37b-11e8-9f18-b9827bf6cd76.PNG)
On the first screen, the equations for quadratic terms and the curve overlap.
![img_1323](https://user-images.githubusercontent.com/41024075/47225669-e1f26f00-d37b-11e8-892d-e5e90973ceb5.PNG)
Orange point covers focus label.
![img_1324](https://user-images.githubusercontent.com/41024075/47225670-e28b0580-d37b-11e8-80b4-cc26e197d0d9.PNG)

**Comment by pixelzoom** [comment]
Thanks for reporting this @KatieWoe.  We have previously identified case of overlap, and addressed the cases that we considered significant.  See https://github.com/phetsims/graphing-quadratics/issues/39.    I don't see any above that we didn't previously evaluate, but I'll leave this open for @amanda-phet to evaluate.

**Comment by KatieWoe** [comment]
![overlaps](https://user-images.githubusercontent.com/41024075/47232439-e96e4400-d38c-11e8-8306-64199b499fee.PNG)

**Comment by pixelzoom** [comment]
The above case (NO REAL ROOTS overlapping vertex) is one that I could probably figure out how to address relatively easily.   @amanda-phet's call.

**Comment by KatieWoe** [comment]
![lap](https://user-images.githubusercontent.com/41024075/47242290-89d36100-d3ab-11e8-80ee-e8e43c94947c.PNG)

**Comment by pixelzoom** [comment]
The above case (overlapping point tools) does not need to be handled. The user can simply move one of the point tools.

**Comment by KatieWoe** [comment]
When two lines overlap only one can be seen.  This includes only one equation.  Note that both y=bx and y=c are checked, but only y=bx can be seen.  @amanda-phet 
![lines](https://user-images.githubusercontent.com/41024075/47316862-5ee44980-d605-11e8-8cbe-99f7bb65336b.PNG)

**Comment by pixelzoom** [comment]
@amanda-phet Each case that you need to review and comment on is indicated by a checklist item in this issue.

**Comment by amanda-phet** [comment]
For "no real roots", I've been aware of this overlap and decided we can live with it because the user can choose to hide either the vertex or the roots. However, if you think there is a workaround, I'd be interested in pursuing it. Perhaps in that specific case, "no real roots" gets bumped above or below the x-axis to accommodate the vertex? Or the vertex coordinates go to the side? I wouldn't spend too much time on it, but it seems like one of these options could easily work (I think I like my second suggestion best). 

In the "two lines overlap" case, both the lines and the equations overlap, and I wonder if there is a way to show both equations so it's clear there are two overlapping lines. This is a low priority to me, though, so I wouldn't spend too much time on it.

**Comment by pixelzoom** [comment]
> For "no real roots", I've been aware of this overlap and decided we can live with it because the user can choose to hide either the vertex or the roots. However, if you think there is a workaround, I'd be interested in pursuing it. Perhaps in that specific case, "no real roots" gets bumped above or below the x-axis to accommodate the vertex? Or the vertex coordinates go to the side? I wouldn't spend too much time on it, but it seems like one of these options could easily work (I think I like my second suggestion best).

Yes, the plan would be to move "NO REAL ROOTS" above or below the x-axis, depending on where the the vertex is.   The downside is that "NO REAL ROOTS" would be jumping around, rather than always be in the same location.  Let me know if you want me to make this change.

> In the "two lines overlap" case, both the lines and the equations overlap, and I wonder if there is a way to show both equations so it's clear there are two overlapping lines. This is a low priority to me, though, so I wouldn't spend too much time on it.

This would involve curves knowing about other curves, and adapting where they put their equation based on whether other curves put their equation.  That's currently not possible, and it's a big change.  So it sounds like you do not want me to spend time on this, but please verify.

**Comment by amanda-phet** [comment]
>Yes, the plan would be to move "NO REAL ROOTS" above or below the x-axis, depending on where the the vertex is. The downside is that "NO REAL ROOTS" would be jumping around, rather than always be in the same location. Let me know if you want me to make this change.

What about the idea to move the vertex coordinates to the side, instead of moving no real roots around? If that is not a reasonable option, then I prefer to leave as-is. 

>This would involve curves knowing about other curves, and adapting where they put their equation based on whether other curves put their equation. That's currently not possible, and it's a big change. So it sounds like you do not want me to spend time on this, but please verify.

Correct, do not spend any further time on this issue.

**Comment by pixelzoom** [comment]
> What about the idea to move the vertex coordinates to the side, instead of moving no real roots around? If that is not a reasonable option, then I prefer to leave as-is.

I could try that, but it will involve making the vertex point know about whether there are any roots. Not terribly difficult, just a little more complicated.

**Comment by pixelzoom** [comment]
> What about the idea to move the vertex coordinates to the side, instead of moving no real roots around? If that is not a reasonable option, then I prefer to leave as-is.

Since this is the only case that we decided to attempt to address, I've moved it to its own issue. See #88.  

Closing this issue.
