### ISSUE TITLE
[IE] "Report a Problem" information is blank

### ISSUE THREAD

**Issue by rea-laura** [phetsims/graphing-quadratics#85]
<b>Test Device</b>

  Dell Laptop (Shrodinger)

  <b>Operating System</b>

  Windows 8.1 Enterprise

  <b>Browser</b>

  Internet Explorer 11.0.9600.19155

  <b>Problem Description</b>

For https://github.com/phetsims/QA/issues/211:
When "Report a Problem" link is clicked, it leads to a page with no troubleshooting info

  <b>Steps to Reproduce</b>

1) open sim
2) select the "PhET" icon in the bottom right corner
3) select "Report a Problem..."
4) this will open a new tab with no troubleshooting info

**Comment by pixelzoom** [comment]
I tested this on Win7 + IE 11.0.9600.17420, and the "Report a Problem" menu item works fine for me.

**Comment by mattpen** [comment]
@KatieWoe - I'm not sure how I can help here.  Why am I assigned?

**Comment by pixelzoom** [comment]
Over in a Slack dev-public, @phet-steele said "the error I receive says it is a problem with the url, so my first guess is @matt (but this error could be a red herring)".  So I believe that's how @mattpen got assigned.   But in a later chat with me, @phet-steele said "this got a bit more complicated", 
"the error is based on query param usage" and "the sim with no qp is fine".    So I'm going to reassign this to @phet-steele, because it sounds like he has some more important information.

**Comment by mattpen** [comment]
@phet-steele contacted me on Slack with further information.  To recreate the problem, you have to run the sim on IE11 with the query parameter `profiler`.  It probably works with some other query params too, but its not clear which. 

The resulting error is : "The URI to be decoded is not a valid encoding".

It appears that this is likely due to the URI being truncated because it is over 2083 characters long, which appears to be the maximum length [that IE can process](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).  We'll either need to reduce the amount of data processed by this page or build a backend that can handle it as POST data.

**Comment by pixelzoom** [comment]
@mattpen am I correct in inferring that this problem is not specific to Graphing Quadratics?

**Comment by mattpen** [comment]
> @mattpen am I correct in inferring that this problem is not specific to Graphing Quadratics?

Correct.  If we're going to fix it, it will require work in joist (I think?) and website.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet.  

* Is this a blocking issue for publication of Graphing Quadratics 1.0?  If so, please label this issue as such.
* Please assign and prioritize.

**Comment by KatieWoe** [comment]
@pixelzoom and @phet-steele I just tried it with the dev version again, no query parameters, and the issue still occurs.  I checked masses and springs (fairly recent pub) with and with out a query parameter and it did not occur.

**Comment by mattpen** [comment]
@KatieWoe - The problem doesn't occur because the resulting URL is under 2083 characters.  If you add some query parameters, it still works but the dependencies gets truncated so there is still a problem.  It would probably fail completely if there was an ampersand at the breakpoint.

![image](https://user-images.githubusercontent.com/11747676/47372375-dcac6180-d6a6-11e8-81ad-346b0c7a0542.png)

**Comment by ariel-phet** [comment]
@pixelzoom not a blocking issue. Leaving assigned to myself, and deferring for the moment.

**Comment by pixelzoom** [comment]
Since this is a general issue that affects all sims, it should be moved to an issue in a common-code repo.  Based on @mattpen's response in https://github.com/phetsims/graphing-quadratics/issues/85#issuecomment-432079597, I'll move this to joist.

**Comment by pixelzoom** [comment]
Move to https://github.com/phetsims/joist/issues/533 with same assignee and priority.

Closing because this is not specific to graphing-quadratics, and is not a prerequisite for publication.

**Comment by rea-laura** [comment]
Also found in https://github.com/phetsims/QA/issues/219
Device: Schrodinger
OS: Windows 8.1
Browser: Internet Explorer 11.0.9600.19155
Only occurs in query parameter ?rtl - all other queries normal.

**Comment by rea-laura** [comment]
Also found in https://github.com/phetsims/QA/issues/243
Device: Bates
OS: Windows 7
Browser: IE 11

**Comment by mattpen** [comment]
@rea-laura - This issue is closed, can you please move these comments to https://github.com/phetsims/joist/issues/533
